name: Update GitHub Activity

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contribution streak
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=PawanForge&theme=tokyonight&hide_border=true&disable_animations=true
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated streak
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/streak.svg

          git diff --cached --quiet || git commit -m "Update GitHub activity"

          git push
